### PR TITLE
Logger v1

### PR DESCRIPTION
**Pull request by camirmas**
Implemented a simple `Logger` that fits into the supervision tree, and that will restore its state upon crashing.

Next steps:
- Potentially consider using ETS (maybe stress test first?)
- Add some configurability options

### CODE REVIEW

**Comment by slurmulon** [comment]
Just curious, what is the justification in renaming `stash` to `hook_server`?

**Comment by camirmas** [comment]
With different `GenServer`s for keeping state in both `Hook` and `Logger` I thought it would be better to rename them to be more specific. I also updated the file structure in a different branch, `file_structure`, to organize a bit more. Ends up looking like this: 

```
lib
├── grapple
│   ├── hook
│   │   ├── hook.ex
│   │   ├── hook_server.ex
│   │   └── hook_supervisor.ex
│   ├── logger
│   │   ├── logger.ex
│   │   ├── log_server.ex
│   │   └── log_supervisor.ex
│   ├── plug.ex
│   └── supervisor.ex
└── grapple.ex

3 directories, 9 files
```

**Comment by slurmulon** [comment]
Okay, makes sense. One concern I have is just that `*_server` might make some people's code a bit harder to understand in the context of a web application - generally you have one server (unless it's microservices or something) so it might be a small trip, but I think it's fine since it's prefixed with `hook_` and `log_`

**Comment by camirmas** [comment]
Good point, though in this case it should be fine because the user of the app will not directly interact with these modules, as their sole purpose is to provide state for the supervisors and workers (`Logger` and `Hook`) and to be as simple as possible so that they never crash.

**Pull request merged**
